# docker-compose.yml
version: '3.8'

services:
  fastapi:
    build: .
    command: bash -c "cd backend && uvicorn main:app --host 0.0.0.0"
    volumes:
      - .:/backend
    ports:
      - 8009:8000
    env_file:
      - backend/.env


